name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.16

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Check for linting errors
        run: bun run lint

      - name: Check for formatting errors
        run: bun run format

      - name: Publish to NPM
        run: bunx pkg-pr-new publish
